name: "Workflow to build Java project"

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout codebase"
        uses: actions/checkout@v3

      - name: "Set up JDK 17"
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: "Build with Maven"
        run: mvn -ntp clean package